// react/src/App.tsx
import React, { useState } from 'react';
import { Speler, Zetten } from './types';
import { Veld } from './Veld';

export function App() {
    const [speler, setSpeler] = useState<Speler>('Kruisje');
    const [aantal, setAantal] = useState<number>(0);
    const [zetten, setZetten] = useState<Zetten>({});
    const [winnendeRij, setWinnendeRij] = useState<string[]>([]);
    const gewonnen: boolean = winnendeRij.length === 3;
    const klaar = (n: number = aantal, rij: string[] = winnendeRij): boolean => rij.length === 3 || n >= 9;
    const message = gewonnen ? `${speler} heeft gewonnen` : klaar() ? 
        'Gelijkspel' : `${speler} is aan de beurt`;
    const bepaalWinnendeRij = (id: string, speler: Speler) => {
        return [
            ["a1", "a2", "a3"], ["b1", "b2", "b3"], ["c1", "c2", "c3"],
            ["a1", "b1", 'c1'], ["a2", "b2", 'c2'], ["a3", "b3", 'c3'],
            ['a1', 'b2', 'c3'], ['a3', 'b2', 'c1']
        ].filter(r => r.includes(id))
            .find(r => r.every(e => zetten[e] === speler)) || [];
    }
    const wissel = () => setSpeler(speler === 'Kruisje' ? 'Nulletje' : 'Kruisje');
    const verwerkZet = (id: string) => {
        if (!klaar()) {
            setAantal(aantal+1);
            zetten[id] = speler;
            setZetten(zetten);
            const rij = bepaalWinnendeRij(id, speler);
            if (rij.length === 3) {
                setWinnendeRij(rij);
            }
            if (!klaar(aantal + 1, rij)) {
                wissel();
            }
        }
    };
    const opnieuw = () => {
        wissel();
        setAantal(0);
        setZetten({});
        setWinnendeRij([]);
    };
    const kolommen = (r: string) => {
        return [1, 2, 3].map(k => r + k).map(id => {
            return <Veld key={id} 
                        id={id} 
                        zetten={zetten} 
                        winnendeRij={winnendeRij} 
                        onGezet={verwerkZet}/>;
        });
    };
    const rijen = ['a', 'b', 'c'].map(r => <div key={r}>{kolommen(r)}</div>);
    return (
        <div id="app">
            <h1>{message}</h1>
            {rijen}
            {klaar() && <button onClick={opnieuw}>Opnieuw</button>}
        </div>
    );
}

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Speler, Zetten } from './types';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  speler: Speler = "Kruisje";
  aantal: number = 0;
  zetten: Zetten = {};
  winnendeRij: string[] = [];

  get gewonnen(): boolean {
      return this.winnendeRij.length === 3;
  }

  get klaar(): boolean {
      return this.gewonnen || this.aantal >= 9;
  }

  get message(): string {
    let m: string;
    if (this.gewonnen) {
      m = `${this.speler} heeft gewonnen!`;
    } else if (this.klaar) {
      m = "Gelijkspel";
    } else {
      m = `${this.speler} is aan de beurt`
    }
    return m;
  }

  bepaalWinnendeRij(id: string, speler: Speler): string[] {
      return [
          ["a1", "a2", "a3"], ["b1", "b2", "b3"], ["c1", "c2", "c3"],
          ["a1", "b1", 'c1'], ["a2", "b2", 'c2'], ["a3", "b3", 'c3'],
          ['a1', 'b2', 'c3'], ['a3', 'b2', 'c1']
      ].filter(r => r.includes(id))
        .find(r => r.every(e => this.zetten[e] === speler)) || [];
  }

  wissel() {
      this.speler = this.speler == 'Kruisje' ? 'Nulletje' : "Kruisje"
  }

  verwerkZet(id: string) {
      this.aantal++;
      const zz = {...this.zetten};
      zz[id] = this.speler;
      this.zetten = zz;
      this.winnendeRij.push(...this.bepaalWinnendeRij(id, this.speler));
      if (!this.klaar) {
          this.wissel();
      }
  }

  opnieuw() {
    this.wissel();
    this.aantal = 0;
    this.zetten = {};
    this.winnendeRij = [];
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div id="app">
  <h1>{{ message }}</h1>
  <div>
    <app-veld [zetten]="zetten" id="a1" [winnende-rij]="winnendeRij" (gezet)="verwerkZet($event)"></app-veld>
    <app-veld [zetten]="zetten" id="a2" [winnende-rij]="winnendeRij" (gezet)="verwerkZet($event)"></app-veld>
    <app-veld [zetten]="zetten" id="a3" [winnende-rij]="winnendeRij" (gezet)="verwerkZet($event)"></app-veld>
  </div>
  <div>
    <app-veld [zetten]="zetten" id="b1" [winnende-rij]="winnendeRij" (gezet)="verwerkZet($event)"></app-veld>
    <app-veld [zetten]="zetten" id="b2" [winnende-rij]="winnendeRij" (gezet)="verwerkZet($event)"></app-veld>
    <app-veld [zetten]="zetten" id="b3" [winnende-rij]="winnendeRij" (gezet)="verwerkZet($event)"></app-veld>
  </div>
  <div>
    <app-veld [zetten]="zetten" id="c1" [winnende-rij]="winnendeRij" (gezet)="verwerkZet($event)"></app-veld>
    <app-veld [zetten]="zetten" id="c2" [winnende-rij]="winnendeRij" (gezet)="verwerkZet($event)"></app-veld>
    <app-veld [zetten]="zetten" id="c3" [winnende-rij]="winnendeRij" (gezet)="verwerkZet($event)"></app-veld>
  </div>
  <button *ngIf="klaar" (click)="opnieuw()">Opnieuw</button>
</div>
